#homework 1

num1 = 50                    #შევქმენი ცვლადი რომელსაც სახელად დავარქვი num1 და ცვლადის მნიშვნელობად მივანიჭე 50
num2 = 25                    #შევქმენი ცვლადი რომელსაც სახელად დავარქვი num2 და ცვლადის მნიშვნელობად მივანიჭე 25
print(num1 + num2)           #დავპრინტე ცვლადები და შვასრულე მათემატიკური ოპერაციები: მიმატება (+)
print(num1-num2)             #დავპრინტე ცვლადები და შვასრულე მათემატიკური ოპერაციები: გამოკლება (-)
print(num1*num2+num2/num1)   #დავპრინტე ცვლადები და შვასრულე მათემატიკური ოპერაციები: გამრავლება (*), მიმატება(+), გაყოფა(/)


#homework 2

age = 13
age_in_5_year=age+5
print(age_in_5_year)


#homework 3

Age = 13
age = 32
print(Age * age)


#homework 4

age = 33
age_in_5_year=age+5
print(age_in_5_year)

age = 32
age_in_5_year=age+5
print(age_in_5_year)

age = 8
age_in_5_year=age+5
print(age_in_5_year)

age = 13
age_in_5_year=age+5
print(age_in_5_year)
 

 #homework 5

name = "gabrieli"
name = "saba"
print(name)


